{% set name = "mdformat-footnote" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mdformat_footnote-{{ version }}.tar.gz
  sha256: d8e6a7fece0f902f0c7dfbd009c093182b9b523527ae48f57f57506d79ccb4ec

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=2,<4
    - pip
  run:
    - python >={{ python_min }}
    - mdformat >=0.7.8,<0.8.0
    - mdit-py-plugins

test:
  imports:
    - mdformat_footnote
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/gaige/mdformat-footnote
  summary: An mdformat plugin for parsing/validating footnotes
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/gaige/mdformat-footnote
  doc_url: https://github.com/executablebooks/mdformat-footnote/blob/master/README.md

extra:
  recipe-maintainers:
    - xylar
